name: aiharp
favicon: null
layout_spectrum: 0.09803876979276538
typography_spectrum: 0.758477951399982
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.21633829083293676
  lightness: 0.5277320649474859
  saturation: 0.9452230476308614
  rhythmicContrast: 0.4788516047410667
purpose: []
